libvirt: fix build with glibc-2.36
add only necessary definitions from linux/fs.h, because including whole
causes conflicts with sys/mount.h:

| In file included from /path/to/tmp-glibc/work/core2-32-wrs-linux/libvirt/8.1.0-r0/recipe-sysroot/usr/include/linux/fs.h:19,
|                  from ../libvirt-8.1.0/src/util/virfile.c:74:
| /path/to/tmp-glibc/work/core2-32-wrs-linux/libvirt/8.1.0-r0/recipe-sysroot/usr/include/linux/mount.h:95:6: error: redeclaration of 'enum fsconfig_command'
|    95 | enum fsconfig_command {
|       |      ^~~~~~~~~~~~~~~~
| In file included from ../libvirt-8.1.0/src/util/virfile.c:46:
| /path/to/tmp-glibc/work/core2-32-wrs-linux/libvirt/8.1.0-r0/recipe-sysroot/usr/include/sys/mount.h:189:6: note: originally defined here
|   189 | enum fsconfig_command
|       |      ^~~~~~~~~~~~~~~~
| /path/to/tmp-glibc/work/core2-32-wrs-linux/libvirt/8.1.0-r0/recipe-sysroot/usr/include/linux/mount.h:96:9: error: redeclaration of enumerator 'FSCONFIG_SET_FLAG'
|    96 |         FSCONFIG_SET_FLAG       = 0,    /* Set parameter, supplying no value */
|       |         ^~~~~~~~~~~~~~~~~

Issue: LINUXEXEC-22065

(LOCAL REV: NOT UPSTREAM) -- send to meta-virtualization on 20220825

Signed-off-by: Kai Kang <kai.kang@windriver.com>

Rebased on 20230130.

Signed-off-by: Kai Kang <kai.kang@windriver.com>