kernel/cfg: add CONFIG_CGROUP_BPF to docker config
Issue: LIN1023-4030

Add CONFIG_CGROUP_BPF to ensure docker can be started under cgroup v2,
otherwise it would report the following error:

     Error: for ... error setting cgroup config for procHooks process:
     bpf_prog_query(BPF_CGROUP_DEVICE) failed: invalid argument: unknown

Cgroup v2 device controller has no interface files and is implemented on top
of cgroup BPF. To control access to device files, a user may create bpf programs
of type BPF_PROG_TYPE_CGROUP_DEVICE and attach them to cgroups with
BPF_CGROUP_DEVICE flag.

On meta-virtualization master, those kernel config fragments has been moved to
yocto-kernel-cache for kernel 6.6, so this change cannot apply to meta-virt
upstream anymore, marked it as a local patch.

(LOCAL REV: NOT UPSTREAM) -- Not applicable, upstream out of maintenance

Signed-off-by: Xiangyu Chen <xiangyu.chen@windriver.com>