podman: convert to rdepends on virtual-runc
Issue: LINCD-6774

After commit (263e4d3d virtual/runc: don't rprovide virtual/) applied
in meta-virtualization, the rdepends changed to virtual-runc, so change
rdepends accordingly in podman recipe to fix below error:
 $ bitbake podman
ERROR: Nothing RPROVIDES 'virtual/runc' (but /buildarea/layers/meta-virtualization/recipes-containers/podman/podman_3.3.1.bb RDEPENDS on or otherwise requires it)

(LOCAL REV: NOT UPSTREAM) -- WRLinux Specific

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>